config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('seller/', include('seller.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', views.UserCreateDoneTV.as_view(), name='register_done'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('order_detail/<int:pk>/',views.order_detail, name='order_detail'),
    path('modify_cart/', views.modify_cart, name='modify_cart'),
]

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'
urlpatterns = [
    path('',views.seller_index, name='seller_index'),
    path('add_food/', views.add_food, name ='add_food'),
    path('food_detail/<int:pk>/', views.food_detail, name='food_detail'),
    path('food_delete/<int:pk>/', views.food_delete, name ='food_delete'),
]

order/models.py
from django.db import models
from seller.models import Food
from django.contrib.auth.models import User

# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)

    def __str__(self):
        return self.name

seller/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Food(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # 상품 판매자
    name = models.CharField(max_length=20)
    price = models.IntegerField()
    description = models.TextField()
    image_url = models.URLField()

config/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView,TemplateView
from django.urls import reverse_lazy
from seller.models import Food

def index(request):
    food = Food.objects.all()

    context = {
        'object' : food
    }
    return render(request, 'home.html', context)

class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

order/views.py
from django.shortcuts import render
from seller.models import Food
from .models import Cart
from django.http import JsonResponse
from django.db.models import Sum

# Create your views here.

def order_detail(request,pk):
    food = Food.objects.get(pk=pk)
    context = {
        'object' : food
    }
    return render(request, 'order/order_detail.html', context)

def modify_cart(request):
    # A사용자가 카트에 담은 B음식에 대해서 수량을 조정하는 내용
    # 응답 : 새롭게 변경된 수량, 전체 카트 음식 수량
    # 어떤 사용자?
    user = request.user
    # 어떤 음식?
    food_id = request.POST['foodId']
    food = Food.objects.get(pk=food_id)
    # 카트 정보
    cart, created = Cart.objects.get_or_create(food=food, user=user)
    # 수량 업데이트
    cart.amount += int(request.POST['amountChange'])
    if cart.amount > 0:
        cart.save()
    # 장바구니 전체 수량 나타내기
    total_quantity = Cart.objects.aggregate(total_quantity=Sum('amount'))['total_quantity']
    # JSON
    context = {
        'newQuantity' : cart.amount,
        'totalQuantity' : total_quantity,
        'message' : '성공',
        'success' : True
    }
    
    return JsonResponse(context)

def order_recipe(request):
    cart = Cart.objects.get(user=request.user)
    
    pass

seller/views.py
from django.shortcuts import render, redirect
from .models import Food
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

# 자신이 판매하는 상품 리스트를 보여주기
# -> 전체 Food에서 특정 user(판매자)인 food만 가져온다
# -> 전체 Food에서 내가 올린 food만 filter한다

# 상품 등록 기능

@login_required
def seller_index(request):
    # foods = Food.objects.all().filter(user__id=request.user.id) # 본인 user__id랑 request user id가 같은것만 뜨게 필터링
    foods = Food.objects.filter(user = request.user)
    context = {
        'object_list': foods
    }

    return render(request, 'seller/seller_index.html', context)

@login_required
def add_food(request):
    # get과 post로 나눠서 처리하자
    if request.method == 'GET':
        return render(request, 'seller/seller_add_food.html')
    elif request.method == 'POST':
        # form에서 전달하는 각 값을 뽑아와서 DB에 저장
        # food_name, price, description
        # category = Category.objects.get(name=request.POST['category']) # forign Key는 인스턴스로 가져와야함
        user = request.user
        food_name = request.POST['name']
        food_price = request.POST['price']
        food_description = request.POST['description']

        fs = FileSystemStorage()
        uploaded_file = request.FILES['file']
        name = fs.save(uploaded_file.name, uploaded_file)
        url = fs.url(name)

        Food.objects.create(user=user, name=food_name, price=food_price, description = food_description, image_url = url)

        return redirect('seller:seller_index')

@login_required  
def food_detail(request,pk):
    food = Food.objects.get(pk=pk)

    context = {
        'object': food
    }

    return render(request, 'seller/seller_food_detail.html', context)

def food_delete(request,pk):
    object = Food.objects.get(pk=pk)
    object.delete()
    return redirect('seller:seller_index')

order/templates/order/order_detail.html
{% extends 'base.html' %}

{% block content %}


    
<title>음식 상세 정보</title>
<!-- 부트스트랩 CDN -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
<style>
    .card {
        max-width: 450px;
        margin: 0 auto;
    }
    .card img {
        max-width: 100%;
        height: auto;
    }

    .food_image img{
        max-width: 450px;
        height: auto;
    }
</style>


    
<div class="container mt-5">
    <div class = "row justify-content-center">
        <div class = "col-md-6 mt-5 text-center">
            <div class = "food_image">
                <img src="{{ object.image_url }}" class="img-fluid rounded" alt="{{object.name}}">
            </div>
        </div>
        <div class = "col-md-6">
            <!-- 음식정보 -->
            <div class = "card mt-5">
                <div class = "card-body">
                    <h3 class="card-title text-center mb-4"><strong>{{object.name}}</strong></h3>
                    <div class = "mb-3">
                        <h5 class = "card-subtitle mb-2"><strong>가격 : {{object.price}}</strong></h5>
                        <p class = "card-text">{{object.description}}</p>
                        <hr>
                    </div>
                    <div>
                        <input type="hidden" id="csrfToken" value="{{csrf_token}}">
                        <button type="button" class = "btn btn-outline-secondary" onclick="modifyCartAmount({{object.id}}, 1)"><i class = "bi bi-arrow-up"></i></button>
                        <button type ="button" class = "btn btn-light border-0">현재수량<span class = 'badge bg-secondary'><span id = 'currentQuantity'></span></button>
                        <button type="button" class = "btn btn-outline-secondary"onclick="modifyCartAmount({{object.id}}, -1)"><i class = "bi bi-arrow-down"></i></button>
                    </div>

                    <div class = "mt-2">
                        <span class="badge bg-dark">총 가격</span>
                        <h2><span id = "totalprice" data-price = "{{ object.price }}"></span></h2>
                    </div>
                    <div>
                        <form action = "" method = "post">
                        {% csrf_token %}
                            <button type = "submit" class = "btn btn-outline-primary">장바구니 담기</button>

                        </form>
                    </div>
    
                </div>
            </div>
        </div>
    </div>
</div>


<!-- 부트스트랩 자바스크립트 CDN -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script>
    function getCsrfToken(){
    return document.getElementById('csrfToken').value;
    }
    function modifyCartAmount(food_id, change){
        var xhr = new XMLHttpRequest();
            xhr.open('POST', '{% url "order:modify_cart" %}', true);
            xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
            xhr.setRequestHeader('X-CSRFToken', getCsrfToken());

            xhr.onload = function() {
                if (this.status === 200) {
                    var response = JSON.parse(this.responseText);
                    document.getElementById('currentQuantity').textContent = response.newQuantity;
                    //document.getElementById('totalQuantity').textContent = response.totalQuantity;

                    var currentQuantity = response.newQuantity;
                    var totalPriceUnit = document.getElementById('totalprice');
                    var pricePerUnit = parseFloat(totalPriceUnit.getAttribute('data-price'));
                    var totalPrice = currentQuantity * pricePerUnit;
                    totalPriceUnit.textContent = totalPrice;

                    console.log(totalPrice)

                    console.log('Update successful:', response.message);
                } else {
                    console.error('Error updating:', this.statusText);
                }
            };
            xhr.send(`foodId=${food_id}&amountChange=${change}`);
    }
</script>


{% endblock %}

seller/templates/seller/seller_add_food.html
{% extends 'base.html' %}

{%block content%}

<div class="container">
    <h1>상품 등록 페이지</h1>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class = "row g-3 mb-3"></div>
            <div class="col-md-4">
                <label for="name" class="form-label">음식이름 :</label>
                <input type="text" name="name" class="form-control" id = "name">
            </div>
            <div class="col-md-4">
                <label for="price" class="form-label">가격 :</label>
                <input type="text" name="price" class="form-control" id="price">
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">설명</label>
                <textarea name="description" rows="2" class="form-control" rows="4" cols="50"></textarea>
            </div>

            <div class="mb-3">
                <label for="file" class="form-label">사진을 올려주세요 :</label>
                <input type="file" name="file" class="form-control" id = "file">
            </div>
        </div>
        <div class ="text-center">
            <input type="submit" value="제출" class="btn btn-primary">
        </div>
    </form>
</div>

<!-- 부트스트랩 자바스크립트 CDN -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

seller/templates/seller/seller_food_detail.html
{% extends 'base.html' %}


{% block content %}

<style>
    .card {
        max-width: 400px;
        margin: 0 auto;
    }
    .card img {
        max-width: 100%;
        height: auto;
    }
</style>

<body>
    <div class="container mt-5">
        <div class="card mt-5">
            <div class="card-body">
                <h3 class="card-title text-center mb-4">음식 상세 정보</h3>
                <div class="mb-3">
                    <h5 class="card-subtitle mb-2 text-muted">판매자</h5>
                    <p class="card-text">{{ user }}</p>
                </div>
                <div class="mb-3">
                    <h5 class="card-subtitle mb-2 text-muted">음식이름</h5>
                    <p class="card-text">{{ object.name }}</p>
                </div>
                <div class="mb-3">
                    <h5 class="card-subtitle mb-2 text-muted">가격</h5>
                    <p class="card-text">{{ object.price }}</p>
                </div>
                <div class="mb-3">
                    <h5 class="card-subtitle mb-2 text-muted">상세설명</h5>
                    <p class="card-text">{{ object.description }}</p>
                </div>
                <div>
                    <img src="{{ object.image_url }}" class="card-img-top" alt="음식 이미지">
                </div>

            <form action = "{% url 'seller:food_delete' pk=object.id %}" method = "post">
                {% csrf_token %}
                <button type = "submit" class = "btn btn-danger mt-2">삭제하기</button>
            </form>
        </div>
    </div>


{% endblock %}

seller/templates/seller/seller_index.html
{% extends 'base.html' %}

{% block content %}

<style>
    .card-img-top {
        width: 100%;
        height: 200px; /* 원하는 높이 값으로 설정하세요 */
        object-fit: contain; /* 이미지가 카드 바디에 꽉 차도록 설정 */
    }
    a {
       text-decoration-line: none;
       color: black;
    }

    a:hover {
    color : red;
    text-decoration: underline;
    }
</style>

<body>
    <div class = "container">
        <div class="row justify-content-center"> <!-- 가운데 정렬을 위한 클래스 -->
            <div class="col-md-12 mt-10 text-center"> <!-- 텍스트 가운데 정렬을 위한 클래스 -->
                <h1 class = "mt-4">{{ user }}의 shop입니다</h1>
            </div>
        </div>

    <div class = "row justify-content-center">
        <div class="col-md-12">
            <h3 class="mt-5">음식</h3>
            <div class="row row-cols-1 row-cols-md-5 g-4">
                {% for food in object_list %}
                <div class="col">
                    <div class="card">
                        <a href = "{% url 'seller:food_detail' pk=food.id %}">
                            <div class = "card-body">
                                <div class = "row">
                                    <div class = "col-md-12 mb-2">
                                        <img src="{{ food.image_url }}" class="card-img-top" alt="{{ food.name }}">
                                    </div>
                                    <div class = "col-md-12">
                                        <div class = "card-text">
                                            <h5 class ="card-title">{{food.name}}</h5>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
        <div class="d-flex justify-content-end mb-3">
            <a href="{% url 'seller:add_food' %}" class="btn btn-primary">제품 등록</a>
        </div>
    
    </div>
</body>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}멋사 반점{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block extra-style %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}" style="font-weight: bold; font-style: italic;">멋사 반점</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">상품 리스트</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">고객 게시판</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'seller:seller_index' %}">판매자 페이지</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
                <ul class="navbar-nav ms-auto">
                  <li class="nav-item dropdown">
                      {% if user.is_active %}
                      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarUserDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fas fa-user-circle"></i>&nbsp;{% firstof user.get_short_name user.get_username %}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarUserDropdown">
                          <form action="{% url 'logout' %}" method="post">
                              {% csrf_token %}
                              <button type="submit" class="dropdown-item">Logout</button>
                          </form>
                          <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                      </ul>
                      {% else %}
                      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarAnonymousDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fas fa-user-circle"></i>&nbsp;Anonymous
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarAnonymousDropdown">
                          <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                          <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                      </ul>
                      {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div>
        {% block content %}{% endblock %}
      </div>

      <script src="https://kit.fontawesome.com/c998a172fe.js" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<style>
    .card-img-top {
        width: 100%;
        height: 200px; /* 원하는 높이 값으로 설정하세요 */
        object-fit: contain; /* 이미지가 카드 바디에 꽉 차도록 설정 */
    }
    a {
       text-decoration-line: none;
       color: black;
    }

    a:hover {
    color : red;
    text-decoration: underline;
    }
</style>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h3 class="mt-4">음식</h3>
        <div class="row row-cols-5">
          {% for food in object %}
          <div class="col">
            <div class="card">
              <a href="{% url 'order:order_detail' pk=food.id %}">
                <div class="card-body">
                  <div class="row"> 
                    <div class="col-md-12 mb-2">
                      <img src="{{ food.image_url }}" class="card-img-top" alt="{{ food.name }}">
                    </div>
                    <div class="col-md-12">
                      <div class="card-text">
                        <h5 class="card-title">{{ food.name }}</h5>
                        <p>{{ food.description }}</p>
                        <p class="card-text">{{ food.price }}</p>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock %}